### PR TITLE
[wip] Adds git handler get master ref and apply production tag

### PR DESCRIPTION
**Pull request by zwolf**
Just need a few questions answered to finish this off:

* Where are the ENV vars set? I don't see it in the infrastructure repo or in the production configs, and i can't tell if the `docker-lita` repo is actually used. We can set something up through the org for this but it'd be easier to just use a generated access token linked to my github account.

* How do I test this? I spent way longer trying to get specs together for this than the actual code, but they all ended up basically just stubbing and testing Octokit itself. I tried to get my own Lita running locally but didn't have any luck with either the `lita` or `docker-lita` repos. Since she basically lives in a box under your desk, I thought maybe you'd have a better idea how to test this.

what'd i miss?

### CODE REVIEW

**Review by marten — COMMENTED** [review]
Is updating that tag not something that should be done by jenkins on every deploy? Maybe you can fill me in on what the goal is tomorrow

**Comment by zwolf** [comment]
Sure. I wanted to hack on lita a little bit, but not adding an additional deploy step would probably be better. I imagine it would be the `panoptes-api/container_config/local_start.sh` in the infrastructure repo that would be the place for that call to add the tag in git. Sound right?

**Comment by adammcmaster** [comment]
That script gets run every time an instance boots, so probably not what you're after.

**Comment by zwolf** [comment]
Okay. Maybe it could be done by lita as a part of the deploy command instead of a separate one. Or by a shell command in the Jenkins deploy job, but Jenkins would have to be authenticated to git. Am I getting warmer?

**Comment by adammcmaster** [comment]
Making it part of the deploy command would be tricky because it would need to wait for the Docker Hub build to finish after it pushes the tag. It would work as part of the build command though, if we have Jenkins push the tag and then make the Docker Hub build automatically trigger the AMI build in AWS. So the workflow would be something like:

- We trigger the build with lita
- Lita starts a Jenkins build that updates the tag
- The Docker Hub does its build
- The Docker Hub triggers the existing AMI build job in Jenkins
- We wait for notification that the AMI build is done and then start the deploy; or if we don't care about precisely timing the deploy, the AMI build automatically triggers the deploy.

Jenkins would need some creds for github, so we'd probably need to just create an account for it.

**Pull request closed without merging**
